DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    BID NUMBER(20) NOT NULL,
    TITLE VARCHAR(300) NOT NULL,
    CONTENTS CLOB,
    HITCNT  NUMBER(10) DEFAULT 0,
 	CREATORID VARCHAR2(20) DEFAULT NULL,
 	CREATEDNM VARCHAR2(20) DEFAULT NULL,
 	PASSWORD VARCHAR2(200) DEFAULT NULL,
 	ATCHFILEID CHAR(20) DEFAULT NULL,
    FRSTREGISTPNTTM TIMESTAMP DEFAULT SYSDATE,
    FRSTREGISTERID VARCHAR(50) DEFAULT NULL,
    LASTUPDTPNTTM TIMESTAMP DEFAULT SYSDATE,
    LASTUPDUSRID VARCHAR(50) DEFAULT NULL,
    DELETEDYN CHAR(11) DEFAULT 'N',
    CONSTRAINT BOARD_PK PRIMARY KEY (BID)
);

DROP SEQUENCE BSEQ;
CREATE SEQUENCE BSEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

COMMENT ON column BOARD.BID 			IS '게시물 번호';
COMMENT ON column BOARD.TITLE  			IS '게시물 제목';
COMMENT ON column BOARD.CONTENTS  			IS '게시물 내용';
COMMENT ON column BOARD.HITCNT  			IS '조회수';
COMMENT ON column BOARD.CREATORID  		IS '게시자ID';
COMMENT ON column BOARD.CREATEDNM  		IS '게시자명';
COMMENT ON column BOARD.PASSWORD  			IS '비밀번호';
COMMENT ON column BOARD.ATCHFILEID  		IS '첨부파일 ID';
COMMENT ON column BOARD.FRSTREGISTPNTTM 	IS '최초 등록 시점';
COMMENT ON column BOARD.FRSTREGISTERID 	IS '최초 등록자 ID';
COMMENT ON column BOARD.LASTUPDTPNTTM  	IS '최종 수정 시점';
COMMENT ON column BOARD.LASTUPDUSRID 	IS '최종 수정자 ID';
COMMENT ON column BOARD.DELETEDYN  		IS '삭제 여부';

INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목1', '홈페이지 샘플 공지 내용1', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목2', '홈페이지 샘플 공지 내용2', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목3', '홈페이지 샘플 공지 내용3', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목4', '홈페이지 샘플 공지 내용4', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목5', '홈페이지 샘플 공지 내용5', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목6', '홈페이지 샘플 공지 내용6', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목7', '홈페이지 샘플 공지 내용7', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목8', '홈페이지 샘플 공지 내용8', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목9', '홈페이지 샘플 공지 내용9', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');
INSERT INTO BOARD(BID, TITLE, CONTENTS, HITCNT, CREATORID, CREATEDNM, PASSWORD, ATCHFILEID , FRSTREGISTPNTTM, FRSTREGISTERID, LASTUPDTPNTTM, LASTUPDUSRID, DELETEDYN) VALUES (BSEQ.NEXTVAL, '홈페이지 샘플 공지 제목10', '홈페이지 샘플 공지 내용10', '0', 'admin', '관리자', 'admin', '', SYSDATE, 'admin', SYSDATE, 'admin', 'n');

commit;